### ISSUE TITLE
Black screen instead of playback with 1.0

### ISSUE THREAD

**Issue by paulsnar** [baedert/corebird#339]
As of 1.0, video components (Vine videos, GIFs) don't play with non-1.0 gstreamer, only (apparently) load. Instead of the video the overlay is just a black rectangle.

For example:
![paulsnar_002](https://cloud.githubusercontent.com/assets/3357767/6857199/c8619c30-d40d-11e4-9edd-6d3d7a370155.png)

Also tested with the latest git (as of now 5a215ad).

Some of package versions (latest on archpkg as far as I can tell):

````
GTK 3.14.9
gstreamer 1.4.5
gst-plugins-bad 1.4.5
gst-plugins-good 1.4.5
gst-libav 1.4.5
````

**Comment by Lyude** [comment]
Hi! It looks like I'm getting the same bug. The weird part is though, I only get it when I start up corebird from gnome's applications menu. If I start it up from the terminal with just the simple command `corebird`, playback seems to work perfectly.

**Comment by Lyude** [comment]
Got some useful output. Looks like when it's started as a service, it might not actually be setting up gstreamer:
```
Mar 28 17:06:31 meerkat org.baedert.corebird[3441]: (corebird:25213): GStreamer-CRITICAL **: gst_element_factory_make: assertion 'gst_is_initialized ()' failed
Mar 28 17:06:31 meerkat org.baedert.corebird[3441]: (corebird:25213): GStreamer-CRITICAL **: gst_element_factory_make: assertion 'gst_is_initialized ()' failed
Mar 28 17:06:31 meerkat org.baedert.corebird[3441]: (corebird:25213): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Mar 28 17:06:31 meerkat org.baedert.corebird[3441]: (corebird:25213): GStreamer-CRITICAL **: gst_element_get_bus: assertion 'GST_IS_ELEMENT (element)' failed
Mar 28 17:06:31 meerkat org.baedert.corebird[3441]: (corebird:25213): GStreamer-CRITICAL **: gst_bus_set_sync_handler: assertion 'GST_IS_BUS (bus)' failed
Mar 28 17:06:31 meerkat org.baedert.corebird[3441]: (corebird:25213): GStreamer-CRITICAL **: gst_bus_add_watch_full: assertion 'GST_IS_BUS (bus)' failed
Mar 28 17:06:31 meerkat org.baedert.corebird[3441]: (corebird:25213): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Mar 28 17:06:31 meerkat org.baedert.corebird[3441]: (corebird:25213): GStreamer-CRITICAL **: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed
```

**Comment by paulsnar** [comment]
Indeed, it does happen so. 

Also the playback works just fine when `corebird` is launched through GNOME's Alt+F2 prompt.

**Comment by baedert** [comment]
SHOULD fix damnit

**Comment by paulsnar** [comment]
Just tried running latest (4cdfa00), apparently this is fixed.

**Comment by jc00ke** [comment]
I'm still seeing the blank behavior in Xubuntu 15.04, version 1.0. Should I open a new issue or should we reopen this one?

**Comment by baedert** [comment]
That commit is not part of 1.0. I usually don't bother with micro releases since they won't hit any distribution quick enough anyway. I can do a 1.0.1 for all I care and see if it helps.

**Comment by jc00ke** [comment]
Thanks, that would be great!

**Comment by baedert** [comment]
ok, done

**Comment by jc00ke** [comment]
@baedert I still don't see video or gif with `1.0.1` :frowning: 

```
** (corebird:2374): WARNING **: InlineMediaDownloader.vala:289: Unrecognized image file format(/home/jesse/.cache/corebird/assets/media/633787959540453376_14761655_0.gifv)
```

from [this tweet](https://twitter.com/hvgoenka/status/633298167845355520)

**Comment by baedert** [comment]
Because we don't download gifv files.

**Comment by jc00ke** [comment]
It looks like Twitter has converted some (all?) gifs to gifv. Should I open up a new issue?

**Comment by baedert** [comment]
I don't remember all the details, but IIRC there was some problem with using gifv files, but you can open a new issue and I can look into it in more detail.
