### ISSUE TITLE
Scrolling down seems to skip a lot of timeline

### ISSUE THREAD

**Issue by cpw** [baedert/corebird#413]
This might be related to other issues, but I've noticed that sometimes, when I scroll back a couple of pages, the timeline seems to skip from say 1 hour ago to 12-14 hours ago. The only way to get the missing tweets to show up is to restart corebird. I'm using the 1.1 tag.

By the way, you work nicely using checkinstall to generate a package on Debian sid..

**Comment by baedert** [comment]
Which part of the timeline skips? Are you scrolling down, up, and then back down again? Is the part on the very top missing? I'm missing a lot of information from that bug description.

**Comment by cpw** [comment]
Sorry. I'm at the top of my timeline "now". I scroll down to view recent history. It's not loaded so it loads in (call it 'load set 1', it contains say 1-3 hours in the past). Scroll back to top. Wait a short time. Scroll down again. Loading continues, but from *before* the last load (here, tweets preceding 'load set 1'). So it's forgotten all of the tweets from 'load set 1'.

So the timeline successively loses recent tweet history. My speculation is that you are putting a "I've loaded back to this point in time" memento in memory, but then you're cleaning up "just off screen" tweets, so tweets between "just off screen" and "point in time memento" go away when I scroll back the second time.

**Comment by baedert** [comment]
Made sense that it was broken, I just pushed a few commits and I can't reproduce it anymore.

**Comment by cpw** [comment]
OK. So I just pulled `$ git describe
1.1-65-g71c96e5`
Problems I've noticed: the odd behaviour above is still occuring but in mentions now, not in the main timeline. The main timeline worked perfectly first time I loaded it up, and it scrolled around fine (though pgup seems to be broken, and won't reach the top of the list). However, I noticed that I couldn't go back very far in time at all after the memory had cleared out. And now, after closing and reopening, it seems my timeline is empty?! (It's stuck on a "loading" screen). My guess is your position markers are imposing hard limits on what is visible. Currently, there's no new tweets at me, so my timeline is completely empty, because your limits are "caught up".

**Comment by baedert** [comment]
> the odd behaviour above is still occuring but in mentions now, not in the main timeline.

I can't reproduce that in my mentions, it seems to work.

> However, I noticed that I couldn't go back very far in time at all after the memory had cleared out.

After the memory had cleared out?

> And now, after closing and reopening, it seems my timeline is empty?! 

Did you just hit the rate limit?

> My guess is your position markers are imposing hard limits on what is visible. Currently, there's no new tweets at me, so my timeline is completely empty, because your limits are "caught up".

Can you stop the guessing? It's wrong and not helpful at all.

**Comment by cpw** [comment]
Ah OK. So it was invisibly rate limited. Fair enough.

**Comment by baedert** [comment]
So you can't reproduce it anymore in the mentions timeline and neither in the home timeline?

**Comment by baedert** [comment]
Taking that as a yes.
